version: 2.1

executors:
  node_container:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/ngx-guardian

jobs:
  setup:
    executor: node_container
    steps:
      - checkout
      - restore_cache:
          key: ngx-guardian-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: ngx-guardian-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - persist_to_workspace:
          root: ~/ngx-guardian
          paths:
            - .

  test:
    executor: node_container
    steps:
      - attach_workspace:
          at: ~/ngx-guardian
      - run: npm run test -- --no-watch --no-progress --code-coverage

workflows:

  setup-test:
    jobs:
      - setup
      - test:
          requires:
            - setup